sheet_name : ADC_ADS1115
sheet_file: adc_ads1115.kicad_sch
pcb_file: adc_ads1115.kicad_pcb
size_wh: [30, 20]
properties:
  Comment: ADC ADS1115

left_pins:
  - name: SDA
    type: bidirectional
    net: SDA

  - name: SCL
    type: bidirectional
    net: SCL
