sheet_name: TempSensor
sheet_file: capt_temp.kicad_sch
pcb_file: capt_temp.kicad_pcb
size_wh: [30, 20]

properties:
  Comment: CAN Buffer

left_pins:
  - name: SDA
    type: bidirectional
    net: SDA
  - name: SCL
    type: bidirectional
    net: SCL
