sheet_name : BUZZER0
sheet_file: buzzer.kicad_sch
pcb_file: buzzer.kicad_pcb
at_xy: [0, 0]
size_wh: [30, 20]

properties:
  Comment: Buzzer

left_pins:
  - name: BUZZER_PIN
    type: input
    net:  BUZZER
