sheet_name :  ACC_MAG
sheet_file: acc_mag.kicad_sch
pcb_file: acc_mag.kicad_pcb
size_wh: [30, 20]

properties:
  Comment: Accelerometer and Magnetometer

left_pins:
  - name: SDA
    type: bidirectional
    net: SDA

  - name: SCL
    type: bidirectional
    net: SCL

  - name: INT_MAG
    type: input
    net: INT_MAG
