sheet_name : CANBuffer
sheet_file: can_buffer.kicad_sch
pcb_file: can_buffer.kicad_pcb
at_xy: [0, 0]
size_wh: [30, 20]

properties:
  Comment: CAN Buffer

left_pins:
  - name: CAN_TX
    type: bidirectional
    net: CAN_TX

  - name: CAN_RX
    type: bidirectional
    net: CAN_RX

right_pins:
  - name: CAN_H
    type: bidirectional
    net: CAN_H

  - name: CAN_L
    type: bidirectional
    net: CAN_L

