sheet_name: BME680
sheet_file: s_bme680.kicad_sch
pcb_file: s_bme680.kicad_pcb
at_xy: [0, 0]
size_wh: [30, 20]

properties:
  Comment: Temperature Sensor

pins:
  - name: SDA
    type: bidirectional
    net: SDA

  - name: SCL
    type: bidirectional
    net: SCL
